- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  gz_type_name: "gz.msgs.Twist"
  ros_type_name: "geometry_msgs/msg/Twist"
  direction: BIDIRECTIONAL

- ros_topic_name: "/odom"
  gz_topic_name: "/odom"
  gz_type_name: "gz.msgs.Odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  direction: BIDIRECTIONAL

- ros_topic_name: "/tf"
  gz_topic_name: "/tf"
  gz_type_name: "gz.msgs.Pose_V"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  direction: BIDIRECTIONAL
